[package]
name = "composition"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
dirs = "6.0.0"
regex = "1.11.3"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.7"
