# general settings
respect_gitignore = true
use_color = false
ignore_dotfolders = true
ignore_dotfiles = true
ignore_empty_lines = true

# directories to ignore explicitly
ignored_directories = [
    "node_modules",
    "target",
    "__venv__",
    "__pycache__"
]

# files to ignore explicitly
ignored_files = []

# regex patterns — if a line matches any, it is ignored
excluded_patterns = [
    "^\\s*//",        # C-style single-line comments
    "^\\s*#",         # Python/Bash comments
    "\\bTODO\\b",     # Any line containing 'TODO'
    "^\\s*\\{",       # Lines starting with '{'
    "^\\s*\\}",       # Lines starting with '}'
]

# list of tracked languages
[[tracked]]
display = "Rust"
extensions = ["rs"]

[[tracked]]
display = "Python"
extensions = ["py"]

[[tracked]]
display = "HTML"
extensions = ["html"]

[[tracked]]
display = "CSS"
extensions = ["css", "scss"]

[[tracked]]
display = "JavaScript"
extensions = ["js", "jsx"]

[[tracked]]
display = "TypeScript"
extensions = ["ts", "tsx"]

[[tracked]]
display = "Svelte"
extensions = ["svelte"]

[[tracked]]
display = "C"
extensions = ["c"]

[[tracked]]
display = "C++"
extensions = ["cpp"]

[[tracked]]
display = "C#"
extensions = ["cs"]

[[tracked]]
display = "Bash"
extensions = ["bash", "bashrc", "bashprofile"]

[[tracked]]
display = "Java"
extensions = ["java"]

[[tracked]]
display = "Jupyter Notebook"
extensions = ["ipynb"]

[[tracked]]
display = "Assembly"
extensions = ["asm", "mips"]

[[tracked]]
display = "Go"
extensions = ["go"]

[[tracked]]
display = "Prisma"
extensions = ["prisma"]
