# general settings
respect_gitignore = true
use_color = false
ignore_dotfolders = true
ignore_dotfiles = true
ignore_empty_lines = true

# directories to ignore explicitly
ignored_directories = [
    "node_modules",
    "target",
    "__venv__",
    "__pycache__"
]

# files to ignore explicitly
ignored_files = []

# regex patterns — if a line matches any, it is ignored
excluded_patterns = [
    "^\\s*//",        # C-style single-line comments
    "^\\s*#",         # Python/Bash comments
    "\\bTODO\\b",     # Any line containing 'TODO'
    "^\\s*\\{",       # Lines starting with '{'
    "^\\s*\\}",       # Lines starting with '}'
]

# list of tracked languages
[[tracked]]
display = "Rust"
extensions = ["rs"]

[[tracked]]
display = "Python"
extensions = ["py"]