# general settings
respect_gitignore = true
use_color = false
ignore_dotfolders = true
ignore_dotfiles = true
ignore_empty_lines = true

# directories to ignore explicitly
ignored_directories = [
    "node_modules",
    "target",
    "__venv__",
    "__pycache__"
]

# files to ignore explicitly
ignored_files = []

# regex patterns — if a line matches any, it is ignored
excluded_patterns = [
    # skip lines starting with //
    # "^\\s*//",

    # skip lines starting with #
    "^\\s*#",

    # skip lines containing only braces, brackets, parentheses, commas, or semicolons
    "^\\s*[\\{\\}\\[\\]\\(\\),;]+\\s*$"
]

# list of tracked languages
[[tracked]]
display = "Rust"
extensions = ["rs"]
# excluded_patterns = ["^\\s*//",]

[[tracked]]
display = "Python"
extensions = ["py"]